import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/navbar";
import React from "react";

import useSWR from "swr";

import axios from "../lib/axios";

const fetcher = (url) => axios.get(url).then((res) => res.data);
export default function Home() {
  const { data: products, error } = useSWR("/api/products", fetcher);

  if (error) return <div>failed to load</div>;

  if (!products) return <div>loading...</div>;

  console.log(products);

  return (
    <div>
      <Head>
        <title>Art store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <main className={styles.main}>
        <h1 className={styles.title}>Art store</h1>

        <p className={styles.description}>Buy Art Online.</p>

        <div className={styles.grid}>
          {/* Products */}
          {products.map((product) => (
            <div key={product.id} className={styles.card}>
              <Image
                src={product.image}
                alt={product.name}
                width={500}
                height={500}
              />
              <div className={styles.productInfo}>
                <h2>{product.name}</h2>
                <p>{product.description}</p>
                <p>${product.price}</p>
              </div>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
