import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Nav from "../components/navbar";
import React, { useState } from "react";
import { Button } from "@chakra-ui/react";
import Context from "../context/context";

import useSWR from "swr";

import axios from "../lib/axios";

import { useRouter } from "next/router";

const fetcher = (url) => axios.get(url).then((res) => res.data);
export default function Home() {
  // const [cart, setCart] = useState([]);
  // const addToCart = (product) => {
  //   setCart([...cart, product]);
  // };

  const router = useRouter();
  const { pid } = router.query;
  const { data: products, error } = useSWR("/api/products", fetcher);

  if (error) return <div>failed to load</div>;

  if (!products) return <div>loading...</div>;

  return (
    <div>
      <Head>
        <title>Art store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Context.Consumer>
        {(context) => (
          <main className={styles.main}>
            <h1 className={styles.title}>Art store</h1>

            <p className={styles.description}>Buy Art Online.</p>

            <div className={styles.grid}>
              {/* Products */}
              {products.map((product) => (
                <div key={product.id} className={styles.card}>
                  {/* <Link href="/product/[id]" as={`/product/${product.id}`}> */}
                  <a>
                    <Image
                      src={product.image}
                      alt={product.name}
                      width={500}
                      height={500}
                    />
                    <div className={styles.productInfo}>
                      <h2>{product.name}</h2>
                      <p>{product.description}</p>
                      <p>${product.price}</p>
                    </div>
                  </a>
                  <Button
                    onClick={() => {
                      context.addProductToCart(product);
                    }}
                  >
                    Add to cart
                  </Button>
                  {/* </Link> */}
                </div>
              ))}
            </div>
          </main>
        )}
      </Context.Consumer>

      <footer className={styles.footer}>
        <p>HIT326 | Coded by Meng</p>
      </footer>
    </div>
  );
}
